services:
  netops-helper:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/netops-helper:0.2.2
    container_name: netops-helper
    restart: unless-stopped
    read_only: true
    init: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,nodev,size=64m,mode=1777
      - /run:rw,noexec,nosuid,nodev,size=8m,mode=0755
    volumes:
      - netops-helper-state:/var/lib/netops-helper
    networks:
      - netops-helper
    pids_limit: 128
    mem_limit: 768m
    cpus: 1.5
    stop_grace_period: 15s

networks:
  netops-helper:
    name: netops-helper
    driver: bridge
    enable_ipv6: false
    driver_opts:
      com.docker.network.bridge.name: nh-egress0
    internal: false

volumes:
  netops-helper-state:
    name: netops-helper-state
