"""Curated Cisco IOS, IOS-XE, and NX-OS phase-1 diagnostic queries."""

from __future__ import annotations

from .model import (
    CISCO_IOS_INTERFACE,
    CISCO_IOS_PHYSICAL_INTERFACE,
    CISCO_NXOS_ERRORS_INTERFACE,
    CISCO_NXOS_INTERFACE,
    CISCO_XE_INTERFACE,
    CISCO_XE_PHYSICAL_INTERFACE,
    IPV4_ADDRESS,
    IPV6_ADDRESS,
    NO_SLOTS,
    Query,
)


IOS_QUERIES: dict[str, Query] = {
    "version": Query("show version", NO_SLOTS, "Show software and platform version details."),
    "clock": Query("show clock", NO_SLOTS, "Show the device clock."),
    "interfaces": Query("show interfaces status", NO_SLOTS, "Summarize interface state and VLAN assignment.", high_volume=True),
    "ip_interfaces": Query("show ip interface brief", NO_SLOTS, "Summarize IPv4 interface state and addresses.", high_volume=True),
    "ipv6_interfaces": Query("show ipv6 interface brief", NO_SLOTS, "Summarize IPv6 interface state and addresses.", high_volume=True),
    "route_summary": Query("show ip route summary", NO_SLOTS, "Summarize the IPv4 routing table."),
    "cpu": Query("show processes cpu", NO_SLOTS, "Show CPU utilization by process.", high_volume=True),
    "memory": Query("show processes memory", NO_SLOTS, "Show memory utilization by process.", high_volume=True),
    "interface_details": Query("show interfaces {interface}", CISCO_IOS_INTERFACE, "Show operational details for one enrolled interface."),
    "route_lookup": Query("show ip route {address}", IPV4_ADDRESS, "Look up one enrolled IPv4 route."),
    "ipv6_route_lookup": Query("show ipv6 route {address}", IPV6_ADDRESS, "Look up one enrolled IPv6 route."),
    "inventory": Query("show inventory", NO_SLOTS, "Show installed hardware inventory."),
    "environment": Query("show env all", NO_SLOTS, "Show environmental sensor status."),
    "interface_errors": Query("show interfaces {interface} counters errors", CISCO_IOS_PHYSICAL_INTERFACE, "Show error counters for one enrolled interface."),
    "arp_table": Query("show ip arp", NO_SLOTS, "Show the IPv4 ARP table.", high_volume=True),
    "ipv6_neighbors": Query("show ipv6 neighbors", NO_SLOTS, "Show the IPv6 neighbor table.", high_volume=True),
    "mac_table": Query("show mac address-table", NO_SLOTS, "Show the MAC address table.", high_volume=True),
    "vlans": Query("show vlan brief", NO_SLOTS, "Summarize configured VLAN state.", high_volume=True),
    "lag_summary": Query("show etherchannel summary", NO_SLOTS, "Summarize EtherChannel state and membership.", high_volume=True),
    "lacp_neighbors": Query("show lacp neighbor", NO_SLOTS, "Show LACP neighbor state.", high_volume=True),
    "stp_summary": Query("show spanning-tree summary", NO_SLOTS, "Summarize spanning-tree state.", high_volume=True),
    "lldp_neighbors": Query("show lldp neighbors detail", NO_SLOTS, "Show detailed LLDP neighbor information.", high_volume=True),
    "cdp_neighbors": Query("show cdp neighbors detail", NO_SLOTS, "Show detailed CDP neighbor information.", high_volume=True),
    "bgp_summary": Query("show ip bgp summary", NO_SLOTS, "Summarize IPv4 BGP peer state.", high_volume=True),
    "ospf_neighbors": Query("show ip ospf neighbor", NO_SLOTS, "Show OSPF neighbor state.", high_volume=True),
    "hsrp_summary": Query("show standby brief", NO_SLOTS, "Summarize HSRP state.", high_volume=True),
    "vrrp_summary": Query("show vrrp brief", NO_SLOTS, "Summarize VRRP state.", high_volume=True),
}


IOS_XE_QUERIES: dict[str, Query] = {
    "version": Query("show version", NO_SLOTS, "Show software and platform version details."),
    "clock": Query("show clock", NO_SLOTS, "Show the device clock."),
    "interfaces": Query("show interfaces status", NO_SLOTS, "Summarize interface state and VLAN assignment.", high_volume=True),
    "ip_interfaces": Query("show ip interface brief", NO_SLOTS, "Summarize IPv4 interface state and addresses.", high_volume=True),
    "ipv6_interfaces": Query("show ipv6 interface brief", NO_SLOTS, "Summarize IPv6 interface state and addresses.", high_volume=True),
    "route_summary": Query("show ip route summary", NO_SLOTS, "Summarize the IPv4 routing table."),
    "cpu": Query("show processes cpu", NO_SLOTS, "Show CPU utilization by process.", high_volume=True),
    "memory": Query("show processes memory", NO_SLOTS, "Show memory utilization by process.", high_volume=True),
    "interface_details": Query("show interfaces {interface}", CISCO_XE_INTERFACE, "Show operational details for one enrolled interface."),
    "route_lookup": Query("show ip route {address}", IPV4_ADDRESS, "Look up one enrolled IPv4 route."),
    "ipv6_route_lookup": Query("show ipv6 route {address}", IPV6_ADDRESS, "Look up one enrolled IPv6 route."),
    "inventory": Query("show inventory", NO_SLOTS, "Show installed hardware inventory."),
    "environment": Query("show environment all", NO_SLOTS, "Show environmental sensor status."),
    "interface_errors": Query("show interfaces {interface} counters errors", CISCO_XE_PHYSICAL_INTERFACE, "Show error counters for one enrolled interface."),
    "arp_table": Query("show ip arp", NO_SLOTS, "Show the IPv4 ARP table.", high_volume=True),
    "ipv6_neighbors": Query("show ipv6 neighbors", NO_SLOTS, "Show the IPv6 neighbor table.", high_volume=True),
    "mac_table": Query("show mac address-table", NO_SLOTS, "Show the MAC address table.", high_volume=True),
    "vlans": Query("show vlan brief", NO_SLOTS, "Summarize configured VLAN state.", high_volume=True),
    "lag_summary": Query("show etherchannel summary", NO_SLOTS, "Summarize EtherChannel state and membership.", high_volume=True),
    "lacp_neighbors": Query("show lacp neighbor", NO_SLOTS, "Show LACP neighbor state.", high_volume=True),
    "stp_summary": Query("show spanning-tree summary", NO_SLOTS, "Summarize spanning-tree state.", high_volume=True),
    "lldp_neighbors": Query("show lldp neighbors detail", NO_SLOTS, "Show detailed LLDP neighbor information.", high_volume=True),
    "cdp_neighbors": Query("show cdp neighbors detail", NO_SLOTS, "Show detailed CDP neighbor information.", high_volume=True),
    "bgp_summary": Query("show ip bgp summary", NO_SLOTS, "Summarize IPv4 BGP peer state.", high_volume=True),
    "ospf_neighbors": Query("show ip ospf neighbor", NO_SLOTS, "Show OSPF neighbor state.", high_volume=True),
    "hsrp_summary": Query("show standby brief", NO_SLOTS, "Summarize HSRP state.", high_volume=True),
    "vrrp_summary": Query("show vrrp brief", NO_SLOTS, "Summarize VRRP state.", high_volume=True),
}


NXOS_QUERIES: dict[str, Query] = {
    "version": Query("show version", NO_SLOTS, "Show software and platform version details."),
    "clock": Query("show clock", NO_SLOTS, "Show the device clock."),
    "inventory": Query("show inventory", NO_SLOTS, "Show installed hardware inventory."),
    "environment": Query("show environment", NO_SLOTS, "Show environmental sensor status."),
    "cpu": Query("show processes cpu", NO_SLOTS, "Show CPU utilization by process.", high_volume=True),
    "memory": Query("show processes memory", NO_SLOTS, "Show memory utilization by process.", high_volume=True),
    "interfaces": Query("show interface status", NO_SLOTS, "Summarize interface state and VLAN assignment.", high_volume=True),
    "ip_interfaces": Query("show ip interface brief", NO_SLOTS, "Summarize IPv4 interface state and addresses.", high_volume=True),
    "ipv6_interfaces": Query("show ipv6 interface brief", NO_SLOTS, "Summarize IPv6 interface state and addresses.", high_volume=True),
    "interface_details": Query("show interface {interface}", CISCO_NXOS_INTERFACE, "Show operational details for one enrolled interface."),
    "interface_errors": Query("show interface {interface} counters errors", CISCO_NXOS_ERRORS_INTERFACE, "Show error counters for one enrolled interface."),
    "vlans": Query("show vlan", NO_SLOTS, "Show VLAN state.", high_volume=True),
    "mac_table": Query("show mac address-table", NO_SLOTS, "Show the MAC address table.", high_volume=True),
    "arp_table": Query("show ip arp", NO_SLOTS, "Show the IPv4 ARP table.", high_volume=True),
    "ipv6_neighbors": Query("show ipv6 neighbor", NO_SLOTS, "Show the IPv6 neighbor table.", high_volume=True),
    "lag_summary": Query("show port-channel summary", NO_SLOTS, "Summarize port-channel state and membership.", high_volume=True),
    "lacp_neighbors": Query("show lacp neighbor", NO_SLOTS, "Show LACP neighbor state.", high_volume=True),
    "stp_summary": Query("show spanning-tree summary", NO_SLOTS, "Summarize spanning-tree state.", high_volume=True),
    "lldp_neighbors": Query("show lldp neighbors detail", NO_SLOTS, "Show detailed LLDP neighbor information.", high_volume=True),
    "cdp_neighbors": Query("show cdp neighbors detail", NO_SLOTS, "Show detailed CDP neighbor information.", high_volume=True),
    "route_summary": Query("show ip route summary", NO_SLOTS, "Summarize the IPv4 routing table."),
    "route_lookup": Query("show ip route {address}", IPV4_ADDRESS, "Look up one enrolled IPv4 route."),
    "ipv6_route_lookup": Query("show ipv6 route {address}", IPV6_ADDRESS, "Look up one enrolled IPv6 route."),
    "bgp_sessions": Query("show bgp sessions", NO_SLOTS, "Show BGP session state.", high_volume=True),
    "ospf_neighbors": Query("show ip ospf neighbors", NO_SLOTS, "Show OSPF neighbor state.", high_volume=True),
    "hsrp_summary": Query("show hsrp summary", NO_SLOTS, "Summarize HSRP state.", high_volume=True),
    "vrrp_summary": Query("show vrrp summary", NO_SLOTS, "Summarize VRRP state.", high_volume=True),
    "vpc_status": Query("show vpc brief", NO_SLOTS, "Summarize virtual port-channel state.", high_volume=True),
    "vpc_peer_keepalive": Query("show vpc peer-keepalive", NO_SLOTS, "Show virtual port-channel peer-keepalive status."),
    "vpc_role": Query("show vpc role", NO_SLOTS, "Show the virtual port-channel role."),
}
